name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (or your preferred environment)
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm install # Adjust this command based on your package manager

      - name: Run unit tests
        run: npm test # Adjust this command based on your test command
