name: Build and Push Docker Image

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login szeLernreiseEngFundamentals.azurecr.io -u szeLernreiseEngFundamentals --password-stdin

      # - name: Get last tag and increment version
      #   id: versioning
      #   run: |
      #     # Fetch all tags from GHCR
      #     TAGS=$(curl -s -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
      #     https://ghcr.io/v2/${{ github.actor }}/alpenzauber/tags/list | jq -r '.tags | map(select(test("^[0-9]+\\.[0-9]+$"))) | sort_by(. | tonumber) | last')

      #     # Default to 1.0 if no previous tags exist
      #     if [ -z "$TAGS" ]; then
      #       NEW_TAG="1.0"
      #     else
      #       # Increment version by 0.1
      #       NEW_TAG=$(awk -v tag="$TAGS" 'BEGIN {printf "%.1f", tag + 0.1}')
      #     fi

      #     echo "New tag: $NEW_TAG"
      #     echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        
      - name: Build the Docker image
        run: |
          docker build -t szeLernreiseEngFundamentals.azurecr.io/ipt-goes-cicd:latest .

      - name: Push the Docker image to GHCR
        run: |
          docker push szeLernreiseEngFundamentals.azurecr.io/ipt-goes-cicd:latest

      # - name: Update latest tag (optional)
      #   run: |
      #     docker tag ghcr.io/${{ github.actor }}/alpenzauber:${{ env.NEW_TAG }} ghcr.io/${{ github.actor }}/alpenzauber:latest
      #     docker push ghcr.io/${{ github.actor }}/alpenzauber:latest
