name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # SonarCloud needs the full history

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=cyber-moon_temp-engineering-fundamentals-fork
            -Dsonar.organization=cyber-moon
            -Dsonar.sources=.

  publish-docker-image:
    needs: code-analysis
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Fetch all tags to determine the next version
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Azure Container Registry
        run: |
          # Quick hack for ACR login
          echo "${{ secrets.ACR_PASSWORD }}" | docker login lrengineering.azurecr.io -u LREngineering --password-stdin

      - name: Generate and Push Git Tag for New Version
        id: versioning
        run: |
          # If no tags exist, start with v0.0
          git fetch origin --tags
          LATEST_TAG=$(git tag --list 'v[0-9]*.[0-9]*' | sort -V | tail -n1 || echo "v0.0")

          IFS='.' read -r major patch <<< "$LATEST_TAG"

          FULL_TAG="${major}.$((patch + 1))"

          echo "Determined new version: $FULL_TAG"

          # Set the FULL_TAG as an output for subsequent steps
          echo "full_tag=$FULL_TAG" >> "$GITHUB_OUTPUT"

          # Create and push the new Git tag
          git tag "$FULL_TAG"
          git push origin "$FULL_TAG"

      - name: Build the Docker image
        run: |
          docker build -t lrengineering.azurecr.io/ipt-spins:${{ steps.versioning.outputs.full_tag }} -t lrengineering.azurecr.io/ipt-spins:latest .

      - name: Push the Docker image to ACR
        run: |
          docker push lrengineering.azurecr.io/ipt-spins:${{ steps.versioning.outputs.full_tag }}
          docker push lrengineering.azurecr.io/ipt-spins:latest