name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
    types: # Trigger on pull_request activity types
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # SonarCloud needs the full history

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=cyber-moon_temp-engineering-fundamentals-fork
            -Dsonar.organization=cyber-moon
            -Dsonar.sources=.
            -Dsonar.tests=.

  build-and-push:
    needs: code-analysis
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: |
          # Quick hack for ACR login
          echo "${{ secrets.ACR_PASSWORD }}" | docker login lrengineering.azurecr.io -u LREngineering --password-stdin

      - name: Read and increment version
        id: versioning
        run: |
          VERSION_FILE="VERSION"
          if [ ! -f "$VERSION_FILE" ]; then echo "0.0.0" > $VERSION_FILE; fi
          CURRENT_VERSION=$(cat $VERSION_FILE)
          # Increment the patch version
          NEW_VERSION=$(awk -F. '{print $1"."$2"."$3+1}' $VERSION_FILE)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "$NEW_VERSION" > "$VERSION_FILE"

      - name: Set up SSH Key # for git push to GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "github-actions-tech-user"

      - name: Commit and Push Updated Version
        run: |
          git add VERSION
          git commit -m "Bump version to $NEW_VERSION [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push" # Use 'origin main' for clarity

      - name: Build the Docker image
        run: |
          docker build -t lrengineering.azurecr.io/ipt-spins:$NEW_VERSION -t lrengineering.azurecr.io/ipt-spins:latest .

      - name: Push the Docker image to ACR
        run: |
          docker push lrengineering.azurecr.io/ipt-spins:$NEW_VERSION
          docker push lrengineering.azurecr.io/ipt-spins:latest
