name: Build and Push Docker Image

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is crucial for OIDC authentication
      contents: write # Needed for checking out code and pushing version updates

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # Enable login to Azure Container Registry (ACR) automatically
          enable-AzPSSession: true # This helps with ACR login

      - name: Read and increment version
        id: versioning
        run: |
          VERSION_FILE="VERSION"
          if [ ! -f "$VERSION_FILE" ]; then echo "0.0.0" > $VERSION_FILE; fi
          CURRENT_VERSION=$(cat $VERSION_FILE)
          NEW_VERSION=$(awk -F. '{print $1"."$2"."$3+1}' $VERSION_FILE)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo $NEW_VERSION > $VERSION_FILE

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "github-actions-tech-user"

      - name: Commit and Push Updated Version
        run: |
          git add VERSION
          git commit -m "Bump version to $NEW_VERSION [skip ci]" || echo "No changes to commit"
          git push git@github.com:iptch/engineering-fundamentals.git main || echo "No changes to push"

      - name: Build the Docker image
        run: |
          docker build -t lrengineering.azurecr.io/ipt-spins:$NEW_VERSION -t lrengineering.azurecr.io/ipt-spins:latest .

      - name: Push the Docker image to ACR
        run: |
          docker push lrengineering.azurecr.io/ipt-spins:$NEW_VERSION
          docker push lrengineering.azurecr.io/ipt-spins:latest
