name: Build and Push Docker Image

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login EngFundamentals.azurecr.io -u EngFundamentals --password-stdin

      - name: Get latest tag and increment
        id: get-latest-tag
        run: |
          LATEST_TAG=$(az acr repository show-tags --name EngFundamentals --repository ipt-spins --orderby time_desc --top 1 --output tsv | grep -Eo '[0-9]+(\.[0-9]+)?$' || echo "0.1")
          NEW_TAG=$(awk "BEGIN {print $LATEST_TAG + 0.1}")
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build -t EngFundamentals.azurecr.io/ipt-spins:$NEW_TAG -t EngFundamentals.azurecr.io/ipt-spins:latest .

      - name: Push the Docker image to ACR
        run: |
          docker push EngFundamentals.azurecr.io/ipt-spins:$NEW_TAG
          docker push EngFundamentals.azurecr.io/ipt-spins:latest
